default_language_version:
  python: python3.11

default_stages: [commit, push]

repos:
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit -r src --config pyproject.toml
        language: system
        types: [python]
        pass_filenames: false
